#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=true
#    username: root
#    password: root
#  session:
#    store-type: none
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
#server:
#  port: 8060
##security:
##  basic:
##    enabled: false
##自定义表单登录页，如果不配置将会使用默认的登录跳转页
##fk.security.browser-properties.login-page: /login.html
##自定义登录类型，如果不配置默认以写死的JSON格式传输
##fk.security.browser-properties.login-type: REDIRECT
#fk.security.browser-properties.sign-up-url: /demo-signUp.html
##fk.security.code.image.length: 6
##fk.security.code.image.width: 100
##fk.security.code.image.url: /user/*
#fk.security.social.qq.app-id: 101469084
#fk.security.social.qq.app-secret: 4e3bfc47901e2535a719ac92f49bd1fa
#fk.security.social.filter-processes-url: /qqLogin
#fk.security.social.qq.provider-id: callback.do